#!/bin/sh
# 							-*- makefile -*-
# debian/postrm file for the Debian/GNU Linux r-cran-hmisc package
# Copyright 2004 by Dirk Eddelbuettel <edd@debian.org>

set -e


if test -x /usr/bin/update-menus; then update-menus; fi


exit 0
